#----------web容器配置-------------
server:
  port: 8070
  context-path: /spBoot/admin
 #----------日志配置-------------
logging:
   config:  classpath:config/logback-springboot.xml
#----------路径url、页面相关配置-------------
path:
  version: 0.2                  #控制css，js版本加载
  prefName: spBoot
spring:
#-------------mapper模块的数据库连接池配置--------
  datasource:
      url: jdbc:mysql://localhost:3306/demo?useSSL=true&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
 #-----------common模块的redis连接池配置--------
  redis:
      database: 1
      host: 192.168.35.129
      port: 6379
      password: redis
      maxActive: 7           #可用连接实例的最大数目，默认值为8
      maxWait: 15000         #最大的等待时间，如果超过等待时间，则直接抛出JedisConnectionException
      maxIdle: 7             # 连接池中的最大空闲连接
      minIdle: 0             # 连接池中的最小空闲连接
      timeout: 3000                 #连接超时时间（毫秒）
  resources:
    chain:
      html-application-cache: false
      cache: false                       #读取静态资源文件是否通过缓存，false表示不通过缓存读取
mybatis:
   typeAliasesPackage: com.earl.spBoot.mapper.entity  #mapper模块的实体扫描配置