#----------web容器配置-------------
server:
  port: 8070
  context-path: /spBoot/admin
 #----------日志配置-------------
logging:
   config:  classpath:config/logback-springboot.xml
#----------路径url、页面相关配置-------------
path:
  version: 0.2                  #控制css，js版本加载
  prefName: spBoot
spring:
#-------------mapper模块的数据库连接池配置--------
  datasource:
      url: jdbc:mysql://localhost:3306/demo?useSSL=true&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource      # 使用druid数据连接池
      driverClassName: com.mysql.jdbc.Driver
      filters: stat                                     #插件配置，使用StatFilter监控
      maxActive: 80                                     #最大连接池数量
      initialSize: 30                                   #初始化连接池数量
      maxWait: 15000                                    # 配置获取连接等待超时的时间
      minIdle: 20                                        #最小连接池数量
      timeBetweenEvictionRunsMillis: 60000             #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 300000                #配置一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: select 1                          #用来检测连接是否有效的sql，要求是一个查询语句
      testWhileIdle: true                                #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测
      testOnBorrow: false                                #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      testOnReturn: false                               #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      poolPreparedStatements: false                      #是否缓存preparedStatement-PSCache。PSCache对支持游标的数据库性能提升巨大，如oracle。在mysql下建议关闭。
      maxOpenPreparedStatements: 0                      #当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
 #-----------common模块的redis连接池配置--------
  redis:
      database: 1
      host: 192.168.35.129
      port: 6379
      password: redis
      maxActive: 7           #可用连接实例的最大数目，默认值为8
      maxWait: 15000         #最大的等待时间，如果超过等待时间，则直接抛出JedisConnectionException
      maxIdle: 7             # 连接池中的最大空闲连接
      minIdle: 0             # 连接池中的最小空闲连接
      timeout: 3000                 #连接超时时间（毫秒）
  resources:
    chain:
      html-application-cache: false
      cache: false                       #读取静态资源文件是否通过缓存，false表示不通过缓存读取
mybatis:
   typeAliasesPackage: com.earl.spBoot.mapper.entity  #mapper模块的实体扫描配置